"""add workflows executions events

Revision ID: 25a022cc1986
Revises: 8f1c2a4b6d7e
Create Date: 2026-07-01 16:43:23.775992

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '25a022cc1986'
down_revision: str | None = '8f1c2a4b6d7e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workflows',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('topology', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflows_created_by'), 'workflows', ['created_by'], unique=False)
    op.create_index(op.f('ix_workflows_org_id'), 'workflows', ['org_id'], unique=False)
    op.create_table('workflow_executions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=True),
    sa.Column('workflow_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('input', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('output', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_executions_org_id'), 'workflow_executions', ['org_id'], unique=False)
    op.create_index(op.f('ix_workflow_executions_workflow_id'), 'workflow_executions', ['workflow_id'], unique=False)
    op.create_table('execution_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('execution_id', sa.UUID(), nullable=True),
    sa.Column('protocol_stage', sa.String(length=20), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['execution_id'], ['workflow_executions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_execution_events_execution_id'), 'execution_events', ['execution_id'], unique=False)
    op.create_index(op.f('ix_execution_events_protocol_stage'), 'execution_events', ['protocol_stage'], unique=False)
    # 部分索引：仅索引进行中的执行（设计文档 §8.4）
    op.create_index(
        "ix_workflow_executions_active_status",
        "workflow_executions",
        ["status"],
        postgresql_where=sa.text("status IN ('pending', 'running')"),
    )
    # 时间线倒序查询索引（设计文档 §8.4）
    op.create_index(
        "ix_execution_events_created_at_desc",
        "execution_events",
        [sa.text("created_at DESC")],
    )
    # updated_at 自动更新触发器（execution_events 仅追加，不挂触发器）
    for _table in ("workflows", "workflow_executions"):
        op.execute(
            f"CREATE TRIGGER set_timestamp_{_table} "
            f"BEFORE UPDATE ON {_table} "
            f"FOR EACH ROW EXECUTE FUNCTION trigger_set_timestamp();"
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_execution_events_protocol_stage'), table_name='execution_events')
    op.drop_index(op.f('ix_execution_events_execution_id'), table_name='execution_events')
    op.drop_table('execution_events')
    op.drop_index(op.f('ix_workflow_executions_workflow_id'), table_name='workflow_executions')
    op.drop_index(op.f('ix_workflow_executions_org_id'), table_name='workflow_executions')
    op.drop_table('workflow_executions')
    op.drop_index(op.f('ix_workflows_org_id'), table_name='workflows')
    op.drop_index(op.f('ix_workflows_created_by'), table_name='workflows')
    op.drop_table('workflows')
    # ### end Alembic commands ###
